export enum SupportedLanguage {
  ENGLISH = "en",
  SPANISH = "es",
  FRENCH = "fr",
  GERMAN = "de",
  PORTUGUESE = "pt",
  ITALIAN = "it",
  DUTCH = "nl",
  RUSSIAN = "ru",
  CHINESE = "zh",
  JAPANESE = "ja",
  KOREAN = "ko",
  ARABIC = "ar",
  HINDI = "hi",
  TURKISH = "tr",
  POLISH = "pl",
  SWEDISH = "sv",
  DANISH = "da",
  NORWEGIAN = "no",
  FINNISH = "fi",
  GREEK = "el",
  HEBREW = "he",
  THAI = "th",
  VIETNAMESE = "vi",
  INDONESIAN = "id",
  MALAY = "ms",
  CZECH = "cs",
  SLOVAK = "sk",
  HUNGARIAN = "hu",
  ROMANIAN = "ro",
  BULGARIAN = "bg",
  UKRAINIAN = "uk",
  CATALAN = "ca",
  CROATIAN = "hr",
}

export const DEFAULT_LANGUAGE = SupportedLanguage.ENGLISH;

export const LANGUAGE_NAMES: Record<SupportedLanguage, string> = {
  [SupportedLanguage.ENGLISH]: "English",
  [SupportedLanguage.SPANISH]: "Español",
  [SupportedLanguage.FRENCH]: "Français",
  [SupportedLanguage.GERMAN]: "Deutsch",
  [SupportedLanguage.PORTUGUESE]: "Português",
  [SupportedLanguage.ITALIAN]: "Italiano",
  [SupportedLanguage.DUTCH]: "Nederlands",
  [SupportedLanguage.RUSSIAN]: "Русский",
  [SupportedLanguage.CHINESE]: "中文",
  [SupportedLanguage.JAPANESE]: "日本語",
  [SupportedLanguage.KOREAN]: "한국어",
  [SupportedLanguage.ARABIC]: "العربية",
  [SupportedLanguage.HINDI]: "हिन्दी",
  [SupportedLanguage.TURKISH]: "Türkçe",
  [SupportedLanguage.POLISH]: "Polski",
  [SupportedLanguage.SWEDISH]: "Svenska",
  [SupportedLanguage.DANISH]: "Dansk",
  [SupportedLanguage.NORWEGIAN]: "Norsk",
  [SupportedLanguage.FINNISH]: "Suomi",
  [SupportedLanguage.GREEK]: "Ελληνικά",
  [SupportedLanguage.HEBREW]: "עברית",
  [SupportedLanguage.THAI]: "ไทย",
  [SupportedLanguage.VIETNAMESE]: "Tiếng Việt",
  [SupportedLanguage.INDONESIAN]: "Bahasa Indonesia",
  [SupportedLanguage.MALAY]: "Bahasa Melayu",
  [SupportedLanguage.CZECH]: "Čeština",
  [SupportedLanguage.SLOVAK]: "Slovenčina",
  [SupportedLanguage.HUNGARIAN]: "Magyar",
  [SupportedLanguage.ROMANIAN]: "Română",
  [SupportedLanguage.BULGARIAN]: "Български",
  [SupportedLanguage.UKRAINIAN]: "Українська",
  [SupportedLanguage.CATALAN]: "Català",
  [SupportedLanguage.CROATIAN]: "Hrvatski",
};
